services:
  karolne.ipresso_api:
      class: KarolNet\IPressoApiBundle\IPressoIntegration\IPressoApi
      arguments:
          - "%ipresso_customer_key%"
          - "%ipresso_login%"
          - "%ipresso_password%"
          - "%ipresso_host%"
